// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffrwnxzuphohsbzwxhsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmcndueHp1cGhvaHNiend4aHNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzExOTgsImV4cCI6MjA2NzQwNzE5OH0.71qSgHeCu9dF11Ps5xVpWn7aaXQOf3wyyuef-cqmnLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});